.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH fujicli-backup-export 1  "export "
.SH NAME
fujicli\-backup\-export \- Export backup
.SH SYNOPSIS
\fBfujicli backup export\fR [\fB\-\-force\fR] [\fB\-j\fR|\fB\-\-json\fR] [\fB\-d\fR|\fB\-\-device\fR] [\fB\-v\fR|\fB\-\-verbose\fR]... [\fB\-h\fR|\fB\-\-help\fR] <\fIOUTPUT\fR>
.SH DESCRIPTION
Export backup
.SH OPTIONS
.TP
\fB\-\-force\fR
Replace an existing regular output file
.TP
\fB\-j\fR, \fB\-\-json\fR
Format output using JSON
.TP
\fB\-d\fR, \fB\-\-device\fR \fI<DEVICE>\fR
Manually specify target device using USB <BUS>.<ADDRESS>
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Log extra debugging information (multiple instances increase verbosity)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIOUTPUT\fR>
Output file (use \*(Aq\-\*(Aq to write to stdout)
