.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH fujicli-backup-import 1  "import "
.SH NAME
fujicli\-backup\-import \- Import backup
.SH SYNOPSIS
\fBfujicli backup import\fR [\fB\-\-yes\fR] [\fB\-\-dry\-run\fR] [\fB\-\-recovery\-backup\fR] [\fB\-\-expect\-sha256\fR] [\fB\-\-target\-serial\-sha256\fR] [\fB\-v\fR|\fB\-\-verbose\fR]... [\fB\-\-allow\-stdin\fR] [\fB\-j\fR|\fB\-\-json\fR] [\fB\-d\fR|\fB\-\-device\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIINPUT\fR>
.SH DESCRIPTION
Import backup
.SH OPTIONS
.TP
\fB\-\-yes\fR
Confirm sending the validated backup artifact to the selected camera
.TP
\fB\-\-dry\-run\fR
Validate compatibility without exporting recovery state or restoring
.TP
\fB\-\-recovery\-backup\fR \fI<RECOVERY_BACKUP>\fR
New file that receives the target\*(Aqs current settings before restore
.TP
\fB\-\-expect\-sha256\fR \fI<EXPECT_SHA256>\fR
Expected SHA\-256 of the complete input artifact
.TP
\fB\-\-target\-serial\-sha256\fR \fI<TARGET_SERIAL_SHA256>\fR
Expected SHA\-256 fingerprint of a different target camera serial
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Log extra debugging information (multiple instances increase verbosity)
.TP
\fB\-\-allow\-stdin\fR
Permit destructive import from stdin (also requires \-\-expect\-sha256)
.TP
\fB\-j\fR, \fB\-\-json\fR
Format dry\-run output using JSON
.TP
\fB\-d\fR, \fB\-\-device\fR \fI<DEVICE>\fR
Manually specify target device using USB <BUS>.<ADDRESS>
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIINPUT\fR>
Input file (use \*(Aq\-\*(Aq to read from stdin)
