.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH fujicli-completion 1  "completion "
.SH NAME
fujicli\-completion \- Generate a shell completion script
.SH SYNOPSIS
\fBfujicli completion\fR [\fB\-v\fR|\fB\-\-verbose\fR]... [\fB\-h\fR|\fB\-\-help\fR] <\fISHELL\fR>
.SH DESCRIPTION
Generate a shell completion script
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Log extra debugging information (multiple instances increase verbosity)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISHELL\fR>
Shell whose completion script should be generated
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
bash
.IP \(bu 2
zsh
.IP \(bu 2
fish
.IP \(bu 2
powershell
.RE
