.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH fujicli-device-list 1  "list "
.SH NAME
fujicli\-device\-list \- List cameras
.SH SYNOPSIS
\fBfujicli device list\fR [\fB\-j\fR|\fB\-\-json\fR] [\fB\-v\fR|\fB\-\-verbose\fR]... [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
List cameras
.SH OPTIONS
.TP
\fB\-j\fR, \fB\-\-json\fR
Format output using JSON
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Log extra debugging information (multiple instances increase verbosity)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
