.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH fujicli-simulation-get 1  "get "
.SH NAME
fujicli\-simulation\-get \- Get simulation
.SH SYNOPSIS
\fBfujicli simulation get\fR [\fB\-j\fR|\fB\-\-json\fR] [\fB\-d\fR|\fB\-\-device\fR] [\fB\-v\fR|\fB\-\-verbose\fR]... [\fB\-h\fR|\fB\-\-help\fR] <\fISLOT\fR>
.SH DESCRIPTION
Get simulation
.SH OPTIONS
.TP
\fB\-j\fR, \fB\-\-json\fR
Format output using JSON
.TP
\fB\-d\fR, \fB\-\-device\fR \fI<DEVICE>\fR
Manually specify target device using USB <BUS>.<ADDRESS>
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Log extra debugging information (multiple instances increase verbosity)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISLOT\fR>
Simulation slot number
